services:
  ml-service:
    build:
      context: .
    image: ml-service
    ports:
      - "8000:8000"
    volumes:
      - ./training_data/Elysia.Laps.feather:/training_data/Elysia.Laps.feather
      - ./training_data/Elysia.Packets.feather:/training_data/Elysia.Packets.feather
    stdin_open: true # Allows you to run the container in interactive mode (-it)
    tty: true # Allocate a pseudo-TTY for the container
