from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class BatteryFaultWarnings(_message.Message):
    __slots__ = ("CclReducedDueToAlternateCurrentLimit", "CclReducedDueToChargerLatch", "CclReducedDueToHighCellResistance", "CclReducedDueToHighCellVoltage", "CclReducedDueToHighPackVoltage", "CclReducedDueToHighSoc", "CclReducedDueToTemperature", "DclAndCclReducedDueToCommunicationFailsafe", "DclAndCclReducedDueToVoltageFailsafe", "DclReducedDueToHighCellResistance", "DclReducedDueToLowCellVoltage", "DclReducedDueToLowPackVoltage", "DclReducedDueToLowSoc", "DclReducedDueToTemperature")
    CCLREDUCEDDUETOALTERNATECURRENTLIMIT_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOCHARGERLATCH_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOHIGHCELLRESISTANCE_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOHIGHCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOHIGHPACKVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOHIGHSOC_FIELD_NUMBER: _ClassVar[int]
    CCLREDUCEDDUETOTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    DCLANDCCLREDUCEDDUETOCOMMUNICATIONFAILSAFE_FIELD_NUMBER: _ClassVar[int]
    DCLANDCCLREDUCEDDUETOVOLTAGEFAILSAFE_FIELD_NUMBER: _ClassVar[int]
    DCLREDUCEDDUETOHIGHCELLRESISTANCE_FIELD_NUMBER: _ClassVar[int]
    DCLREDUCEDDUETOLOWCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    DCLREDUCEDDUETOLOWPACKVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    DCLREDUCEDDUETOLOWSOC_FIELD_NUMBER: _ClassVar[int]
    DCLREDUCEDDUETOTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    CclReducedDueToAlternateCurrentLimit: bool
    CclReducedDueToChargerLatch: bool
    CclReducedDueToHighCellResistance: bool
    CclReducedDueToHighCellVoltage: bool
    CclReducedDueToHighPackVoltage: bool
    CclReducedDueToHighSoc: bool
    CclReducedDueToTemperature: bool
    DclAndCclReducedDueToCommunicationFailsafe: bool
    DclAndCclReducedDueToVoltageFailsafe: bool
    DclReducedDueToHighCellResistance: bool
    DclReducedDueToLowCellVoltage: bool
    DclReducedDueToLowPackVoltage: bool
    DclReducedDueToLowSoc: bool
    DclReducedDueToTemperature: bool
    def __init__(self, CclReducedDueToAlternateCurrentLimit: bool = ..., CclReducedDueToChargerLatch: bool = ..., CclReducedDueToHighCellResistance: bool = ..., CclReducedDueToHighCellVoltage: bool = ..., CclReducedDueToHighPackVoltage: bool = ..., CclReducedDueToHighSoc: bool = ..., CclReducedDueToTemperature: bool = ..., DclAndCclReducedDueToCommunicationFailsafe: bool = ..., DclAndCclReducedDueToVoltageFailsafe: bool = ..., DclReducedDueToHighCellResistance: bool = ..., DclReducedDueToLowCellVoltage: bool = ..., DclReducedDueToLowPackVoltage: bool = ..., DclReducedDueToLowSoc: bool = ..., DclReducedDueToTemperature: bool = ...) -> None: ...

class BatteryFaultErrors(_message.Message):
    __slots__ = ("AlwaysOnSupplyFault", "CanbusCommunicationFault", "ChargeLimitEnforcementFault", "ChargerSafetyRelayFault", "CurrentSensorFault", "DischargeLimitEnforcementFault", "FanMonitorFault", "HighVoltageIsolationFault", "InternalCommunicationFault", "InternalConversionFault", "InternalLogicFault", "InternalMemoryFault", "InternalThermistorFault", "LowCellVoltageFault", "OpenWiringFault", "PackVoltageSensorFault", "PowerSupply12VFault", "ThermistorFault", "VoltageRedundancyFault", "WeakCellFault", "WeakPackFault")
    ALWAYSONSUPPLYFAULT_FIELD_NUMBER: _ClassVar[int]
    CANBUSCOMMUNICATIONFAULT_FIELD_NUMBER: _ClassVar[int]
    CHARGELIMITENFORCEMENTFAULT_FIELD_NUMBER: _ClassVar[int]
    CHARGERSAFETYRELAYFAULT_FIELD_NUMBER: _ClassVar[int]
    CURRENTSENSORFAULT_FIELD_NUMBER: _ClassVar[int]
    DISCHARGELIMITENFORCEMENTFAULT_FIELD_NUMBER: _ClassVar[int]
    FANMONITORFAULT_FIELD_NUMBER: _ClassVar[int]
    HIGHVOLTAGEISOLATIONFAULT_FIELD_NUMBER: _ClassVar[int]
    INTERNALCOMMUNICATIONFAULT_FIELD_NUMBER: _ClassVar[int]
    INTERNALCONVERSIONFAULT_FIELD_NUMBER: _ClassVar[int]
    INTERNALLOGICFAULT_FIELD_NUMBER: _ClassVar[int]
    INTERNALMEMORYFAULT_FIELD_NUMBER: _ClassVar[int]
    INTERNALTHERMISTORFAULT_FIELD_NUMBER: _ClassVar[int]
    LOWCELLVOLTAGEFAULT_FIELD_NUMBER: _ClassVar[int]
    OPENWIRINGFAULT_FIELD_NUMBER: _ClassVar[int]
    PACKVOLTAGESENSORFAULT_FIELD_NUMBER: _ClassVar[int]
    POWERSUPPLY12VFAULT_FIELD_NUMBER: _ClassVar[int]
    THERMISTORFAULT_FIELD_NUMBER: _ClassVar[int]
    VOLTAGEREDUNDANCYFAULT_FIELD_NUMBER: _ClassVar[int]
    WEAKCELLFAULT_FIELD_NUMBER: _ClassVar[int]
    WEAKPACKFAULT_FIELD_NUMBER: _ClassVar[int]
    AlwaysOnSupplyFault: bool
    CanbusCommunicationFault: bool
    ChargeLimitEnforcementFault: bool
    ChargerSafetyRelayFault: bool
    CurrentSensorFault: bool
    DischargeLimitEnforcementFault: bool
    FanMonitorFault: bool
    HighVoltageIsolationFault: bool
    InternalCommunicationFault: bool
    InternalConversionFault: bool
    InternalLogicFault: bool
    InternalMemoryFault: bool
    InternalThermistorFault: bool
    LowCellVoltageFault: bool
    OpenWiringFault: bool
    PackVoltageSensorFault: bool
    PowerSupply12VFault: bool
    ThermistorFault: bool
    VoltageRedundancyFault: bool
    WeakCellFault: bool
    WeakPackFault: bool
    def __init__(self, AlwaysOnSupplyFault: bool = ..., CanbusCommunicationFault: bool = ..., ChargeLimitEnforcementFault: bool = ..., ChargerSafetyRelayFault: bool = ..., CurrentSensorFault: bool = ..., DischargeLimitEnforcementFault: bool = ..., FanMonitorFault: bool = ..., HighVoltageIsolationFault: bool = ..., InternalCommunicationFault: bool = ..., InternalConversionFault: bool = ..., InternalLogicFault: bool = ..., InternalMemoryFault: bool = ..., InternalThermistorFault: bool = ..., LowCellVoltageFault: bool = ..., OpenWiringFault: bool = ..., PackVoltageSensorFault: bool = ..., PowerSupply12VFault: bool = ..., ThermistorFault: bool = ..., VoltageRedundancyFault: bool = ..., WeakCellFault: bool = ..., WeakPackFault: bool = ...) -> None: ...

class BatteryFaults(_message.Message):
    __slots__ = ("Errors", "Warnings")
    ERRORS_FIELD_NUMBER: _ClassVar[int]
    WARNINGS_FIELD_NUMBER: _ClassVar[int]
    Errors: BatteryFaultErrors
    Warnings: BatteryFaultWarnings
    def __init__(self, Errors: _Optional[_Union[BatteryFaultErrors, _Mapping]] = ..., Warnings: _Optional[_Union[BatteryFaultWarnings, _Mapping]] = ...) -> None: ...

class BatteryStatus(_message.Message):
    __slots__ = ("AlwaysOnSignalStatus", "AverageCellVoltage", "AverageTemperature", "BmuAlive", "ChargeRelayEnabled", "ChargerSafetyEnabled", "DischargeRelayEnabled", "FanSpeed", "FanVoltage", "HighCellVoltage", "HighCellVoltageId", "HighTemperature", "HighThermistorId", "Input12V", "InternalTemperature", "IsChargingSignalStatus", "IsReadySignalStatus", "LowCellVoltage", "LowCellVoltageId", "LowTemperature", "LowThermistorId", "MalfunctionIndicatorActive", "MaximumCellVoltage", "MaximumPackVoltage", "MinimumCellVoltage", "MinimumPackVoltage", "MultiPurposeInputSignalStatus", "PackAmphours", "PackCurrent", "PackDepthOfDischarge", "PackStateOfCharge", "PackVoltage", "PopulatedCells", "RequestedFanSpeed")
    ALWAYSONSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    AVERAGECELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    AVERAGETEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    BMUALIVE_FIELD_NUMBER: _ClassVar[int]
    CHARGERELAYENABLED_FIELD_NUMBER: _ClassVar[int]
    CHARGERSAFETYENABLED_FIELD_NUMBER: _ClassVar[int]
    DISCHARGERELAYENABLED_FIELD_NUMBER: _ClassVar[int]
    FANSPEED_FIELD_NUMBER: _ClassVar[int]
    FANVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    HIGHCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    HIGHCELLVOLTAGEID_FIELD_NUMBER: _ClassVar[int]
    HIGHTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    HIGHTHERMISTORID_FIELD_NUMBER: _ClassVar[int]
    INPUT12V_FIELD_NUMBER: _ClassVar[int]
    INTERNALTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    ISCHARGINGSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    ISREADYSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    LOWCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    LOWCELLVOLTAGEID_FIELD_NUMBER: _ClassVar[int]
    LOWTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    LOWTHERMISTORID_FIELD_NUMBER: _ClassVar[int]
    MALFUNCTIONINDICATORACTIVE_FIELD_NUMBER: _ClassVar[int]
    MAXIMUMCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MAXIMUMPACKVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MINIMUMCELLVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MINIMUMPACKVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MULTIPURPOSEINPUTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    PACKAMPHOURS_FIELD_NUMBER: _ClassVar[int]
    PACKCURRENT_FIELD_NUMBER: _ClassVar[int]
    PACKDEPTHOFDISCHARGE_FIELD_NUMBER: _ClassVar[int]
    PACKSTATEOFCHARGE_FIELD_NUMBER: _ClassVar[int]
    PACKVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    POPULATEDCELLS_FIELD_NUMBER: _ClassVar[int]
    REQUESTEDFANSPEED_FIELD_NUMBER: _ClassVar[int]
    AlwaysOnSignalStatus: bool
    AverageCellVoltage: float
    AverageTemperature: float
    BmuAlive: float
    ChargeRelayEnabled: bool
    ChargerSafetyEnabled: bool
    DischargeRelayEnabled: bool
    FanSpeed: float
    FanVoltage: float
    HighCellVoltage: float
    HighCellVoltageId: float
    HighTemperature: float
    HighThermistorId: float
    Input12V: float
    InternalTemperature: float
    IsChargingSignalStatus: bool
    IsReadySignalStatus: bool
    LowCellVoltage: float
    LowCellVoltageId: float
    LowTemperature: float
    LowThermistorId: float
    MalfunctionIndicatorActive: bool
    MaximumCellVoltage: float
    MaximumPackVoltage: float
    MinimumCellVoltage: float
    MinimumPackVoltage: float
    MultiPurposeInputSignalStatus: bool
    PackAmphours: float
    PackCurrent: float
    PackDepthOfDischarge: float
    PackStateOfCharge: float
    PackVoltage: float
    PopulatedCells: float
    RequestedFanSpeed: float
    def __init__(self, AlwaysOnSignalStatus: bool = ..., AverageCellVoltage: _Optional[float] = ..., AverageTemperature: _Optional[float] = ..., BmuAlive: _Optional[float] = ..., ChargeRelayEnabled: bool = ..., ChargerSafetyEnabled: bool = ..., DischargeRelayEnabled: bool = ..., FanSpeed: _Optional[float] = ..., FanVoltage: _Optional[float] = ..., HighCellVoltage: _Optional[float] = ..., HighCellVoltageId: _Optional[float] = ..., HighTemperature: _Optional[float] = ..., HighThermistorId: _Optional[float] = ..., Input12V: _Optional[float] = ..., InternalTemperature: _Optional[float] = ..., IsChargingSignalStatus: bool = ..., IsReadySignalStatus: bool = ..., LowCellVoltage: _Optional[float] = ..., LowCellVoltageId: _Optional[float] = ..., LowTemperature: _Optional[float] = ..., LowThermistorId: _Optional[float] = ..., MalfunctionIndicatorActive: bool = ..., MaximumCellVoltage: _Optional[float] = ..., MaximumPackVoltage: _Optional[float] = ..., MinimumCellVoltage: _Optional[float] = ..., MinimumPackVoltage: _Optional[float] = ..., MultiPurposeInputSignalStatus: bool = ..., PackAmphours: _Optional[float] = ..., PackCurrent: _Optional[float] = ..., PackDepthOfDischarge: _Optional[float] = ..., PackStateOfCharge: _Optional[float] = ..., PackVoltage: _Optional[float] = ..., PopulatedCells: _Optional[float] = ..., RequestedFanSpeed: _Optional[float] = ...) -> None: ...

class B3(_message.Message):
    __slots__ = ("Acceleration", "B3Heartbeat", "BrakeLightSignalStatus", "BrakeSwitchDigital", "DaytimeRunningLightSignalStatus", "ForwardDigital", "HandbrakeSwitchDigital", "HazardLightsInput", "HeadightsSwitchInput", "HeadlightSignalStatus", "HornSignalStatus", "HornSwitchDigital", "LapDigital", "LeftSignalInput", "LeftSignalStatus", "MotorResetDigital", "NeutralDigital", "RaceModeDigital", "RegenBraking", "ReverseDigital", "RightSignalInput", "RightSignalStatus")
    ACCELERATION_FIELD_NUMBER: _ClassVar[int]
    B3HEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    BRAKELIGHTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    BRAKESWITCHDIGITAL_FIELD_NUMBER: _ClassVar[int]
    DAYTIMERUNNINGLIGHTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    FORWARDDIGITAL_FIELD_NUMBER: _ClassVar[int]
    HANDBRAKESWITCHDIGITAL_FIELD_NUMBER: _ClassVar[int]
    HAZARDLIGHTSINPUT_FIELD_NUMBER: _ClassVar[int]
    HEADIGHTSSWITCHINPUT_FIELD_NUMBER: _ClassVar[int]
    HEADLIGHTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    HORNSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    HORNSWITCHDIGITAL_FIELD_NUMBER: _ClassVar[int]
    LAPDIGITAL_FIELD_NUMBER: _ClassVar[int]
    LEFTSIGNALINPUT_FIELD_NUMBER: _ClassVar[int]
    LEFTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    MOTORRESETDIGITAL_FIELD_NUMBER: _ClassVar[int]
    NEUTRALDIGITAL_FIELD_NUMBER: _ClassVar[int]
    RACEMODEDIGITAL_FIELD_NUMBER: _ClassVar[int]
    REGENBRAKING_FIELD_NUMBER: _ClassVar[int]
    REVERSEDIGITAL_FIELD_NUMBER: _ClassVar[int]
    RIGHTSIGNALINPUT_FIELD_NUMBER: _ClassVar[int]
    RIGHTSIGNALSTATUS_FIELD_NUMBER: _ClassVar[int]
    Acceleration: float
    B3Heartbeat: bool
    BrakeLightSignalStatus: bool
    BrakeSwitchDigital: bool
    DaytimeRunningLightSignalStatus: bool
    ForwardDigital: bool
    HandbrakeSwitchDigital: bool
    HazardLightsInput: bool
    HeadightsSwitchInput: bool
    HeadlightSignalStatus: bool
    HornSignalStatus: bool
    HornSwitchDigital: bool
    LapDigital: bool
    LeftSignalInput: bool
    LeftSignalStatus: bool
    MotorResetDigital: bool
    NeutralDigital: bool
    RaceModeDigital: bool
    RegenBraking: float
    ReverseDigital: bool
    RightSignalInput: bool
    RightSignalStatus: bool
    def __init__(self, Acceleration: _Optional[float] = ..., B3Heartbeat: bool = ..., BrakeLightSignalStatus: bool = ..., BrakeSwitchDigital: bool = ..., DaytimeRunningLightSignalStatus: bool = ..., ForwardDigital: bool = ..., HandbrakeSwitchDigital: bool = ..., HazardLightsInput: bool = ..., HeadightsSwitchInput: bool = ..., HeadlightSignalStatus: bool = ..., HornSignalStatus: bool = ..., HornSwitchDigital: bool = ..., LapDigital: bool = ..., LeftSignalInput: bool = ..., LeftSignalStatus: bool = ..., MotorResetDigital: bool = ..., NeutralDigital: bool = ..., RaceModeDigital: bool = ..., RegenBraking: _Optional[float] = ..., ReverseDigital: bool = ..., RightSignalInput: bool = ..., RightSignalStatus: bool = ...) -> None: ...

class KeyMotor(_message.Message):
    __slots__ = ("BusCurrentOut", "KeyMotorVelocity", "MotorCurrent")
    BUSCURRENTOUT_FIELD_NUMBER: _ClassVar[int]
    KEYMOTORVELOCITY_FIELD_NUMBER: _ClassVar[int]
    MOTORCURRENT_FIELD_NUMBER: _ClassVar[int]
    BusCurrentOut: float
    KeyMotorVelocity: float
    MotorCurrent: float
    def __init__(self, BusCurrentOut: _Optional[float] = ..., KeyMotorVelocity: _Optional[float] = ..., MotorCurrent: _Optional[float] = ...) -> None: ...

class MBMS(_message.Message):
    __slots__ = ("AbattDisable", "ArrayContactorCommand", "ArrayHeartbeatDeadTrip", "ArrayHighCurrentTrip", "ArrayHighCurrentWarning", "AuxiliaryBatteryVoltage", "CanOc12VWarning", "ChargeContactorCommand", "ChargeEnable", "ChargeHeartbeatDeadTrip", "ChargeHighCurrentTrip", "ChargeHighCurrentWarning", "ChargeSafety", "ChargeShouldTrip", "ChgFault", "ChgLvEn", "ChgOn", "CommonContactorCommand", "CommonHeartbeatDeadTrip", "CommonHighCurrentTrip", "CommonHighCurrentWarning", "ContactorConnectedUnexpectedlyTrip", "ContactorDisconnectedUnexpectedlyTrip", "DcdcFault", "DcdcOn", "DischargeEnable", "DischargeShouldTrip", "En1", "EsdEnabledTrip", "ExternalShutdown", "Heartbeat", "HighCellVoltageTrip", "HighCellVoltageWarning", "HighTemperatureTrip", "HighTemperatureWarning", "Key", "LowCellVoltageTrip", "LowCellVoltageWarning", "LowTemperatureTrip", "LowTemperatureWarning", "LvContactorCommand", "LvHeartbeatDeadTrip", "LvHighCurrentTrip", "LvHighCurrentWarning", "MainPowerSwitch", "MotorContactorCommand", "MotorHeartbeatDeadTrip", "MotorHighCurrentTrip", "MotorHighCurrentWarning", "MpsDisabledTrip", "OrionCanReceivedRecently", "OrionMessageTimeoutTrip", "ProtectionTrip", "StartupState", "StrobeBmsLight", "SystemState", "ThreeAOc")
    ABATTDISABLE_FIELD_NUMBER: _ClassVar[int]
    ARRAYCONTACTORCOMMAND_FIELD_NUMBER: _ClassVar[int]
    ARRAYHEARTBEATDEADTRIP_FIELD_NUMBER: _ClassVar[int]
    ARRAYHIGHCURRENTTRIP_FIELD_NUMBER: _ClassVar[int]
    ARRAYHIGHCURRENTWARNING_FIELD_NUMBER: _ClassVar[int]
    AUXILIARYBATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    CANOC12VWARNING_FIELD_NUMBER: _ClassVar[int]
    CHARGECONTACTORCOMMAND_FIELD_NUMBER: _ClassVar[int]
    CHARGEENABLE_FIELD_NUMBER: _ClassVar[int]
    CHARGEHEARTBEATDEADTRIP_FIELD_NUMBER: _ClassVar[int]
    CHARGEHIGHCURRENTTRIP_FIELD_NUMBER: _ClassVar[int]
    CHARGEHIGHCURRENTWARNING_FIELD_NUMBER: _ClassVar[int]
    CHARGESAFETY_FIELD_NUMBER: _ClassVar[int]
    CHARGESHOULDTRIP_FIELD_NUMBER: _ClassVar[int]
    CHGFAULT_FIELD_NUMBER: _ClassVar[int]
    CHGLVEN_FIELD_NUMBER: _ClassVar[int]
    CHGON_FIELD_NUMBER: _ClassVar[int]
    COMMONCONTACTORCOMMAND_FIELD_NUMBER: _ClassVar[int]
    COMMONHEARTBEATDEADTRIP_FIELD_NUMBER: _ClassVar[int]
    COMMONHIGHCURRENTTRIP_FIELD_NUMBER: _ClassVar[int]
    COMMONHIGHCURRENTWARNING_FIELD_NUMBER: _ClassVar[int]
    CONTACTORCONNECTEDUNEXPECTEDLYTRIP_FIELD_NUMBER: _ClassVar[int]
    CONTACTORDISCONNECTEDUNEXPECTEDLYTRIP_FIELD_NUMBER: _ClassVar[int]
    DCDCFAULT_FIELD_NUMBER: _ClassVar[int]
    DCDCON_FIELD_NUMBER: _ClassVar[int]
    DISCHARGEENABLE_FIELD_NUMBER: _ClassVar[int]
    DISCHARGESHOULDTRIP_FIELD_NUMBER: _ClassVar[int]
    EN1_FIELD_NUMBER: _ClassVar[int]
    ESDENABLEDTRIP_FIELD_NUMBER: _ClassVar[int]
    EXTERNALSHUTDOWN_FIELD_NUMBER: _ClassVar[int]
    HEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    HIGHCELLVOLTAGETRIP_FIELD_NUMBER: _ClassVar[int]
    HIGHCELLVOLTAGEWARNING_FIELD_NUMBER: _ClassVar[int]
    HIGHTEMPERATURETRIP_FIELD_NUMBER: _ClassVar[int]
    HIGHTEMPERATUREWARNING_FIELD_NUMBER: _ClassVar[int]
    KEY_FIELD_NUMBER: _ClassVar[int]
    LOWCELLVOLTAGETRIP_FIELD_NUMBER: _ClassVar[int]
    LOWCELLVOLTAGEWARNING_FIELD_NUMBER: _ClassVar[int]
    LOWTEMPERATURETRIP_FIELD_NUMBER: _ClassVar[int]
    LOWTEMPERATUREWARNING_FIELD_NUMBER: _ClassVar[int]
    LVCONTACTORCOMMAND_FIELD_NUMBER: _ClassVar[int]
    LVHEARTBEATDEADTRIP_FIELD_NUMBER: _ClassVar[int]
    LVHIGHCURRENTTRIP_FIELD_NUMBER: _ClassVar[int]
    LVHIGHCURRENTWARNING_FIELD_NUMBER: _ClassVar[int]
    MAINPOWERSWITCH_FIELD_NUMBER: _ClassVar[int]
    MOTORCONTACTORCOMMAND_FIELD_NUMBER: _ClassVar[int]
    MOTORHEARTBEATDEADTRIP_FIELD_NUMBER: _ClassVar[int]
    MOTORHIGHCURRENTTRIP_FIELD_NUMBER: _ClassVar[int]
    MOTORHIGHCURRENTWARNING_FIELD_NUMBER: _ClassVar[int]
    MPSDISABLEDTRIP_FIELD_NUMBER: _ClassVar[int]
    ORIONCANRECEIVEDRECENTLY_FIELD_NUMBER: _ClassVar[int]
    ORIONMESSAGETIMEOUTTRIP_FIELD_NUMBER: _ClassVar[int]
    PROTECTIONTRIP_FIELD_NUMBER: _ClassVar[int]
    STARTUPSTATE_FIELD_NUMBER: _ClassVar[int]
    STROBEBMSLIGHT_FIELD_NUMBER: _ClassVar[int]
    SYSTEMSTATE_FIELD_NUMBER: _ClassVar[int]
    THREEAOC_FIELD_NUMBER: _ClassVar[int]
    AbattDisable: bool
    ArrayContactorCommand: bool
    ArrayHeartbeatDeadTrip: bool
    ArrayHighCurrentTrip: bool
    ArrayHighCurrentWarning: bool
    AuxiliaryBatteryVoltage: float
    CanOc12VWarning: bool
    ChargeContactorCommand: bool
    ChargeEnable: bool
    ChargeHeartbeatDeadTrip: bool
    ChargeHighCurrentTrip: bool
    ChargeHighCurrentWarning: bool
    ChargeSafety: bool
    ChargeShouldTrip: bool
    ChgFault: bool
    ChgLvEn: bool
    ChgOn: bool
    CommonContactorCommand: bool
    CommonHeartbeatDeadTrip: bool
    CommonHighCurrentTrip: bool
    CommonHighCurrentWarning: bool
    ContactorConnectedUnexpectedlyTrip: bool
    ContactorDisconnectedUnexpectedlyTrip: bool
    DcdcFault: bool
    DcdcOn: bool
    DischargeEnable: bool
    DischargeShouldTrip: bool
    En1: bool
    EsdEnabledTrip: bool
    ExternalShutdown: bool
    Heartbeat: bool
    HighCellVoltageTrip: bool
    HighCellVoltageWarning: bool
    HighTemperatureTrip: bool
    HighTemperatureWarning: bool
    Key: bool
    LowCellVoltageTrip: bool
    LowCellVoltageWarning: bool
    LowTemperatureTrip: bool
    LowTemperatureWarning: bool
    LvContactorCommand: bool
    LvHeartbeatDeadTrip: bool
    LvHighCurrentTrip: bool
    LvHighCurrentWarning: bool
    MainPowerSwitch: bool
    MotorContactorCommand: bool
    MotorHeartbeatDeadTrip: bool
    MotorHighCurrentTrip: bool
    MotorHighCurrentWarning: bool
    MpsDisabledTrip: bool
    OrionCanReceivedRecently: bool
    OrionMessageTimeoutTrip: bool
    ProtectionTrip: bool
    StartupState: float
    StrobeBmsLight: bool
    SystemState: float
    ThreeAOc: bool
    def __init__(self, AbattDisable: bool = ..., ArrayContactorCommand: bool = ..., ArrayHeartbeatDeadTrip: bool = ..., ArrayHighCurrentTrip: bool = ..., ArrayHighCurrentWarning: bool = ..., AuxiliaryBatteryVoltage: _Optional[float] = ..., CanOc12VWarning: bool = ..., ChargeContactorCommand: bool = ..., ChargeEnable: bool = ..., ChargeHeartbeatDeadTrip: bool = ..., ChargeHighCurrentTrip: bool = ..., ChargeHighCurrentWarning: bool = ..., ChargeSafety: bool = ..., ChargeShouldTrip: bool = ..., ChgFault: bool = ..., ChgLvEn: bool = ..., ChgOn: bool = ..., CommonContactorCommand: bool = ..., CommonHeartbeatDeadTrip: bool = ..., CommonHighCurrentTrip: bool = ..., CommonHighCurrentWarning: bool = ..., ContactorConnectedUnexpectedlyTrip: bool = ..., ContactorDisconnectedUnexpectedlyTrip: bool = ..., DcdcFault: bool = ..., DcdcOn: bool = ..., DischargeEnable: bool = ..., DischargeShouldTrip: bool = ..., En1: bool = ..., EsdEnabledTrip: bool = ..., ExternalShutdown: bool = ..., Heartbeat: bool = ..., HighCellVoltageTrip: bool = ..., HighCellVoltageWarning: bool = ..., HighTemperatureTrip: bool = ..., HighTemperatureWarning: bool = ..., Key: bool = ..., LowCellVoltageTrip: bool = ..., LowCellVoltageWarning: bool = ..., LowTemperatureTrip: bool = ..., LowTemperatureWarning: bool = ..., LvContactorCommand: bool = ..., LvHeartbeatDeadTrip: bool = ..., LvHighCurrentTrip: bool = ..., LvHighCurrentWarning: bool = ..., MainPowerSwitch: bool = ..., MotorContactorCommand: bool = ..., MotorHeartbeatDeadTrip: bool = ..., MotorHighCurrentTrip: bool = ..., MotorHighCurrentWarning: bool = ..., MpsDisabledTrip: bool = ..., OrionCanReceivedRecently: bool = ..., OrionMessageTimeoutTrip: bool = ..., ProtectionTrip: bool = ..., StartupState: _Optional[float] = ..., StrobeBmsLight: bool = ..., SystemState: _Optional[float] = ..., ThreeAOc: bool = ...) -> None: ...

class MotorDetails(_message.Message):
    __slots__ = ("ActiveMotor", "BEMF_D", "BEMF_Q", "BusCurrent", "BusVoltage", "DC_Bus_Ah", "DspBoardTemperature", "ErrorFlags", "HeatsinkTemperature", "Id", "Iq", "LimitFlags", "MotorId", "MotorTemperature", "MotorVelocity", "Odometer", "PhaseCurrentB", "PhaseCurrentC", "RxErrorCount", "SerialNumber", "SlipSpeed", "Supply15V", "Supply1V9", "Supply3V3", "TritiumId", "TxErrorCount", "Vd", "VehicleVelocity", "Vq")
    ACTIVEMOTOR_FIELD_NUMBER: _ClassVar[int]
    BEMF_D_FIELD_NUMBER: _ClassVar[int]
    BEMF_Q_FIELD_NUMBER: _ClassVar[int]
    BUSCURRENT_FIELD_NUMBER: _ClassVar[int]
    BUSVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    DC_BUS_AH_FIELD_NUMBER: _ClassVar[int]
    DSPBOARDTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    ERRORFLAGS_FIELD_NUMBER: _ClassVar[int]
    HEATSINKTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    ID_FIELD_NUMBER: _ClassVar[int]
    IQ_FIELD_NUMBER: _ClassVar[int]
    LIMITFLAGS_FIELD_NUMBER: _ClassVar[int]
    MOTORID_FIELD_NUMBER: _ClassVar[int]
    MOTORTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MOTORVELOCITY_FIELD_NUMBER: _ClassVar[int]
    ODOMETER_FIELD_NUMBER: _ClassVar[int]
    PHASECURRENTB_FIELD_NUMBER: _ClassVar[int]
    PHASECURRENTC_FIELD_NUMBER: _ClassVar[int]
    RXERRORCOUNT_FIELD_NUMBER: _ClassVar[int]
    SERIALNUMBER_FIELD_NUMBER: _ClassVar[int]
    SLIPSPEED_FIELD_NUMBER: _ClassVar[int]
    SUPPLY15V_FIELD_NUMBER: _ClassVar[int]
    SUPPLY1V9_FIELD_NUMBER: _ClassVar[int]
    SUPPLY3V3_FIELD_NUMBER: _ClassVar[int]
    TRITIUMID_FIELD_NUMBER: _ClassVar[int]
    TXERRORCOUNT_FIELD_NUMBER: _ClassVar[int]
    VD_FIELD_NUMBER: _ClassVar[int]
    VEHICLEVELOCITY_FIELD_NUMBER: _ClassVar[int]
    VQ_FIELD_NUMBER: _ClassVar[int]
    ActiveMotor: float
    BEMF_D: float
    BEMF_Q: float
    BusCurrent: float
    BusVoltage: float
    DC_Bus_Ah: float
    DspBoardTemperature: float
    ErrorFlags: float
    HeatsinkTemperature: float
    Id: float
    Iq: float
    LimitFlags: float
    MotorId: float
    MotorTemperature: float
    MotorVelocity: float
    Odometer: float
    PhaseCurrentB: float
    PhaseCurrentC: float
    RxErrorCount: float
    SerialNumber: float
    SlipSpeed: float
    Supply15V: float
    Supply1V9: float
    Supply3V3: float
    TritiumId: float
    TxErrorCount: float
    Vd: float
    VehicleVelocity: float
    Vq: float
    def __init__(self, ActiveMotor: _Optional[float] = ..., BEMF_D: _Optional[float] = ..., BEMF_Q: _Optional[float] = ..., BusCurrent: _Optional[float] = ..., BusVoltage: _Optional[float] = ..., DC_Bus_Ah: _Optional[float] = ..., DspBoardTemperature: _Optional[float] = ..., ErrorFlags: _Optional[float] = ..., HeatsinkTemperature: _Optional[float] = ..., Id: _Optional[float] = ..., Iq: _Optional[float] = ..., LimitFlags: _Optional[float] = ..., MotorId: _Optional[float] = ..., MotorTemperature: _Optional[float] = ..., MotorVelocity: _Optional[float] = ..., Odometer: _Optional[float] = ..., PhaseCurrentB: _Optional[float] = ..., PhaseCurrentC: _Optional[float] = ..., RxErrorCount: _Optional[float] = ..., SerialNumber: _Optional[float] = ..., SlipSpeed: _Optional[float] = ..., Supply15V: _Optional[float] = ..., Supply1V9: _Optional[float] = ..., Supply3V3: _Optional[float] = ..., TritiumId: _Optional[float] = ..., TxErrorCount: _Optional[float] = ..., Vd: _Optional[float] = ..., VehicleVelocity: _Optional[float] = ..., Vq: _Optional[float] = ...) -> None: ...

class MPPT(_message.Message):
    __slots__ = ("Mppt0Ch0ArrayCurrent", "Mppt0Ch0ArrayVoltage", "Mppt0Ch0BatteryVoltage", "Mppt0Ch0UnitTemperature", "Mppt0Ch1ArrayCurrent", "Mppt0Ch1ArrayVoltage", "Mppt0Ch1BatteryVoltage", "Mppt0Ch1UnitTemperature", "Mppt1Ch0ArrayCurrent", "Mppt1Ch0ArrayVoltage", "Mppt1Ch0BatteryVoltage", "Mppt1Ch0UnitTemperature", "Mppt1Ch1ArrayCurrent", "Mppt1Ch1ArrayVoltage", "Mppt1Ch1BatteryVoltage", "Mppt1Ch1UnitTemperature", "Mppt2Ch0ArrayCurrent", "Mppt2Ch0ArrayVoltage", "Mppt2Ch0BatteryVoltage", "Mppt2Ch0UnitTemperature", "Mppt2Ch1ArrayCurrent", "Mppt2Ch1ArrayVoltage", "Mppt2Ch1BatteryVoltage", "Mppt2Ch1UnitTemperature", "Mppt3Ch0ArrayCurrent", "Mppt3Ch0ArrayVoltage", "Mppt3Ch0BatteryVoltage", "Mppt3Ch0UnitTemperature", "Mppt3Ch1ArrayCurrent", "Mppt3Ch1ArrayVoltage", "Mppt3Ch1BatteryVoltage", "Mppt3Ch1UnitTemperature")
    MPPT0CH0ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH0ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH0BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH0UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH1ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH1ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH1BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT0CH1UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH0ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH0ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH0BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH0UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH1ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH1ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH1BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT1CH1UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH0ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH0ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH0BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH0UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH1ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH1ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH1BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT2CH1UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH0ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH0ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH0BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH0UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH1ARRAYCURRENT_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH1ARRAYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH1BATTERYVOLTAGE_FIELD_NUMBER: _ClassVar[int]
    MPPT3CH1UNITTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    Mppt0Ch0ArrayCurrent: float
    Mppt0Ch0ArrayVoltage: float
    Mppt0Ch0BatteryVoltage: float
    Mppt0Ch0UnitTemperature: float
    Mppt0Ch1ArrayCurrent: float
    Mppt0Ch1ArrayVoltage: float
    Mppt0Ch1BatteryVoltage: float
    Mppt0Ch1UnitTemperature: float
    Mppt1Ch0ArrayCurrent: float
    Mppt1Ch0ArrayVoltage: float
    Mppt1Ch0BatteryVoltage: float
    Mppt1Ch0UnitTemperature: float
    Mppt1Ch1ArrayCurrent: float
    Mppt1Ch1ArrayVoltage: float
    Mppt1Ch1BatteryVoltage: float
    Mppt1Ch1UnitTemperature: float
    Mppt2Ch0ArrayCurrent: float
    Mppt2Ch0ArrayVoltage: float
    Mppt2Ch0BatteryVoltage: float
    Mppt2Ch0UnitTemperature: float
    Mppt2Ch1ArrayCurrent: float
    Mppt2Ch1ArrayVoltage: float
    Mppt2Ch1BatteryVoltage: float
    Mppt2Ch1UnitTemperature: float
    Mppt3Ch0ArrayCurrent: float
    Mppt3Ch0ArrayVoltage: float
    Mppt3Ch0BatteryVoltage: float
    Mppt3Ch0UnitTemperature: float
    Mppt3Ch1ArrayCurrent: float
    Mppt3Ch1ArrayVoltage: float
    Mppt3Ch1BatteryVoltage: float
    Mppt3Ch1UnitTemperature: float
    def __init__(self, Mppt0Ch0ArrayCurrent: _Optional[float] = ..., Mppt0Ch0ArrayVoltage: _Optional[float] = ..., Mppt0Ch0BatteryVoltage: _Optional[float] = ..., Mppt0Ch0UnitTemperature: _Optional[float] = ..., Mppt0Ch1ArrayCurrent: _Optional[float] = ..., Mppt0Ch1ArrayVoltage: _Optional[float] = ..., Mppt0Ch1BatteryVoltage: _Optional[float] = ..., Mppt0Ch1UnitTemperature: _Optional[float] = ..., Mppt1Ch0ArrayCurrent: _Optional[float] = ..., Mppt1Ch0ArrayVoltage: _Optional[float] = ..., Mppt1Ch0BatteryVoltage: _Optional[float] = ..., Mppt1Ch0UnitTemperature: _Optional[float] = ..., Mppt1Ch1ArrayCurrent: _Optional[float] = ..., Mppt1Ch1ArrayVoltage: _Optional[float] = ..., Mppt1Ch1BatteryVoltage: _Optional[float] = ..., Mppt1Ch1UnitTemperature: _Optional[float] = ..., Mppt2Ch0ArrayCurrent: _Optional[float] = ..., Mppt2Ch0ArrayVoltage: _Optional[float] = ..., Mppt2Ch0BatteryVoltage: _Optional[float] = ..., Mppt2Ch0UnitTemperature: _Optional[float] = ..., Mppt2Ch1ArrayCurrent: _Optional[float] = ..., Mppt2Ch1ArrayVoltage: _Optional[float] = ..., Mppt2Ch1BatteryVoltage: _Optional[float] = ..., Mppt2Ch1UnitTemperature: _Optional[float] = ..., Mppt3Ch0ArrayCurrent: _Optional[float] = ..., Mppt3Ch0ArrayVoltage: _Optional[float] = ..., Mppt3Ch0BatteryVoltage: _Optional[float] = ..., Mppt3Ch0UnitTemperature: _Optional[float] = ..., Mppt3Ch1ArrayCurrent: _Optional[float] = ..., Mppt3Ch1ArrayVoltage: _Optional[float] = ..., Mppt3Ch1BatteryVoltage: _Optional[float] = ..., Mppt3Ch1UnitTemperature: _Optional[float] = ...) -> None: ...

class ContactorStatus(_message.Message):
    __slots__ = ("ArrayBPSError", "ArrayChargeCurrent", "ArrayContactorClosed", "ArrayContactorClosing", "ArrayContactorError", "ArrayHeartbeat", "ArrayLineCurrent", "ArrayPrechargerClosed", "ArrayPrechargerClosing", "ArrayPrechargerError", "ChargeBPSError", "ChargeChargeCurrent", "ChargeContactorClosed", "ChargeContactorClosing", "ChargeContactorError", "ChargeHeartbeat", "ChargeLineCurrent", "ChargePrechargerClosed", "ChargePrechargerClosing", "ChargePrechargerError", "CommonChargeCurrent", "CommonContactorClosed", "CommonContactorClosing", "CommonContactorError", "CommonContactorOpeningError", "CommonHeartbeat", "CommonLineCurrent", "CommonPrechargerClosed", "CommonPrechargerClosing", "CommonPrechargerError", "LvBpsError", "LvChargeCurrent", "LvContactorClosed", "LvContactorClosing", "LvContactorError", "LvHeartbeat", "LvLineCurrent", "LvPrechargerClosed", "LvPrechargerClosing", "LvPrechargerError", "MotorBPSError", "MotorChargeCurrent", "MotorContactorClosed", "MotorContactorClosing", "MotorContactorError", "MotorHeartbeat", "MotorLineCurrent", "MotorPrechargerClosed", "MotorPrechargerClosing", "MotorPrechargerError")
    ARRAYBPSERROR_FIELD_NUMBER: _ClassVar[int]
    ARRAYCHARGECURRENT_FIELD_NUMBER: _ClassVar[int]
    ARRAYCONTACTORCLOSED_FIELD_NUMBER: _ClassVar[int]
    ARRAYCONTACTORCLOSING_FIELD_NUMBER: _ClassVar[int]
    ARRAYCONTACTORERROR_FIELD_NUMBER: _ClassVar[int]
    ARRAYHEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    ARRAYLINECURRENT_FIELD_NUMBER: _ClassVar[int]
    ARRAYPRECHARGERCLOSED_FIELD_NUMBER: _ClassVar[int]
    ARRAYPRECHARGERCLOSING_FIELD_NUMBER: _ClassVar[int]
    ARRAYPRECHARGERERROR_FIELD_NUMBER: _ClassVar[int]
    CHARGEBPSERROR_FIELD_NUMBER: _ClassVar[int]
    CHARGECHARGECURRENT_FIELD_NUMBER: _ClassVar[int]
    CHARGECONTACTORCLOSED_FIELD_NUMBER: _ClassVar[int]
    CHARGECONTACTORCLOSING_FIELD_NUMBER: _ClassVar[int]
    CHARGECONTACTORERROR_FIELD_NUMBER: _ClassVar[int]
    CHARGEHEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    CHARGELINECURRENT_FIELD_NUMBER: _ClassVar[int]
    CHARGEPRECHARGERCLOSED_FIELD_NUMBER: _ClassVar[int]
    CHARGEPRECHARGERCLOSING_FIELD_NUMBER: _ClassVar[int]
    CHARGEPRECHARGERERROR_FIELD_NUMBER: _ClassVar[int]
    COMMONCHARGECURRENT_FIELD_NUMBER: _ClassVar[int]
    COMMONCONTACTORCLOSED_FIELD_NUMBER: _ClassVar[int]
    COMMONCONTACTORCLOSING_FIELD_NUMBER: _ClassVar[int]
    COMMONCONTACTORERROR_FIELD_NUMBER: _ClassVar[int]
    COMMONCONTACTOROPENINGERROR_FIELD_NUMBER: _ClassVar[int]
    COMMONHEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    COMMONLINECURRENT_FIELD_NUMBER: _ClassVar[int]
    COMMONPRECHARGERCLOSED_FIELD_NUMBER: _ClassVar[int]
    COMMONPRECHARGERCLOSING_FIELD_NUMBER: _ClassVar[int]
    COMMONPRECHARGERERROR_FIELD_NUMBER: _ClassVar[int]
    LVBPSERROR_FIELD_NUMBER: _ClassVar[int]
    LVCHARGECURRENT_FIELD_NUMBER: _ClassVar[int]
    LVCONTACTORCLOSED_FIELD_NUMBER: _ClassVar[int]
    LVCONTACTORCLOSING_FIELD_NUMBER: _ClassVar[int]
    LVCONTACTORERROR_FIELD_NUMBER: _ClassVar[int]
    LVHEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    LVLINECURRENT_FIELD_NUMBER: _ClassVar[int]
    LVPRECHARGERCLOSED_FIELD_NUMBER: _ClassVar[int]
    LVPRECHARGERCLOSING_FIELD_NUMBER: _ClassVar[int]
    LVPRECHARGERERROR_FIELD_NUMBER: _ClassVar[int]
    MOTORBPSERROR_FIELD_NUMBER: _ClassVar[int]
    MOTORCHARGECURRENT_FIELD_NUMBER: _ClassVar[int]
    MOTORCONTACTORCLOSED_FIELD_NUMBER: _ClassVar[int]
    MOTORCONTACTORCLOSING_FIELD_NUMBER: _ClassVar[int]
    MOTORCONTACTORERROR_FIELD_NUMBER: _ClassVar[int]
    MOTORHEARTBEAT_FIELD_NUMBER: _ClassVar[int]
    MOTORLINECURRENT_FIELD_NUMBER: _ClassVar[int]
    MOTORPRECHARGERCLOSED_FIELD_NUMBER: _ClassVar[int]
    MOTORPRECHARGERCLOSING_FIELD_NUMBER: _ClassVar[int]
    MOTORPRECHARGERERROR_FIELD_NUMBER: _ClassVar[int]
    ArrayBPSError: bool
    ArrayChargeCurrent: float
    ArrayContactorClosed: bool
    ArrayContactorClosing: bool
    ArrayContactorError: bool
    ArrayHeartbeat: bool
    ArrayLineCurrent: float
    ArrayPrechargerClosed: bool
    ArrayPrechargerClosing: bool
    ArrayPrechargerError: bool
    ChargeBPSError: bool
    ChargeChargeCurrent: float
    ChargeContactorClosed: bool
    ChargeContactorClosing: bool
    ChargeContactorError: bool
    ChargeHeartbeat: bool
    ChargeLineCurrent: float
    ChargePrechargerClosed: bool
    ChargePrechargerClosing: bool
    ChargePrechargerError: bool
    CommonChargeCurrent: float
    CommonContactorClosed: bool
    CommonContactorClosing: bool
    CommonContactorError: bool
    CommonContactorOpeningError: bool
    CommonHeartbeat: bool
    CommonLineCurrent: float
    CommonPrechargerClosed: bool
    CommonPrechargerClosing: bool
    CommonPrechargerError: bool
    LvBpsError: bool
    LvChargeCurrent: float
    LvContactorClosed: bool
    LvContactorClosing: bool
    LvContactorError: bool
    LvHeartbeat: bool
    LvLineCurrent: float
    LvPrechargerClosed: bool
    LvPrechargerClosing: bool
    LvPrechargerError: bool
    MotorBPSError: bool
    MotorChargeCurrent: float
    MotorContactorClosed: bool
    MotorContactorClosing: bool
    MotorContactorError: bool
    MotorHeartbeat: bool
    MotorLineCurrent: float
    MotorPrechargerClosed: bool
    MotorPrechargerClosing: bool
    MotorPrechargerError: bool
    def __init__(self, ArrayBPSError: bool = ..., ArrayChargeCurrent: _Optional[float] = ..., ArrayContactorClosed: bool = ..., ArrayContactorClosing: bool = ..., ArrayContactorError: bool = ..., ArrayHeartbeat: bool = ..., ArrayLineCurrent: _Optional[float] = ..., ArrayPrechargerClosed: bool = ..., ArrayPrechargerClosing: bool = ..., ArrayPrechargerError: bool = ..., ChargeBPSError: bool = ..., ChargeChargeCurrent: _Optional[float] = ..., ChargeContactorClosed: bool = ..., ChargeContactorClosing: bool = ..., ChargeContactorError: bool = ..., ChargeHeartbeat: bool = ..., ChargeLineCurrent: _Optional[float] = ..., ChargePrechargerClosed: bool = ..., ChargePrechargerClosing: bool = ..., ChargePrechargerError: bool = ..., CommonChargeCurrent: _Optional[float] = ..., CommonContactorClosed: bool = ..., CommonContactorClosing: bool = ..., CommonContactorError: bool = ..., CommonContactorOpeningError: bool = ..., CommonHeartbeat: bool = ..., CommonLineCurrent: _Optional[float] = ..., CommonPrechargerClosed: bool = ..., CommonPrechargerClosing: bool = ..., CommonPrechargerError: bool = ..., LvBpsError: bool = ..., LvChargeCurrent: _Optional[float] = ..., LvContactorClosed: bool = ..., LvContactorClosing: bool = ..., LvContactorError: bool = ..., LvHeartbeat: bool = ..., LvLineCurrent: _Optional[float] = ..., LvPrechargerClosed: bool = ..., LvPrechargerClosing: bool = ..., LvPrechargerError: bool = ..., MotorBPSError: bool = ..., MotorChargeCurrent: _Optional[float] = ..., MotorContactorClosed: bool = ..., MotorContactorClosing: bool = ..., MotorContactorError: bool = ..., MotorHeartbeat: bool = ..., MotorLineCurrent: _Optional[float] = ..., MotorPrechargerClosed: bool = ..., MotorPrechargerClosing: bool = ..., MotorPrechargerError: bool = ...) -> None: ...

class Pi(_message.Message):
    __slots__ = ("Rfid",)
    RFID_FIELD_NUMBER: _ClassVar[int]
    Rfid: str
    def __init__(self, Rfid: _Optional[str] = ...) -> None: ...

class ProximitySensors(_message.Message):
    __slots__ = ("ProximitySensor1", "ProximitySensor2", "ProximitySensor3", "ProximitySensor4")
    PROXIMITYSENSOR1_FIELD_NUMBER: _ClassVar[int]
    PROXIMITYSENSOR2_FIELD_NUMBER: _ClassVar[int]
    PROXIMITYSENSOR3_FIELD_NUMBER: _ClassVar[int]
    PROXIMITYSENSOR4_FIELD_NUMBER: _ClassVar[int]
    ProximitySensor1: float
    ProximitySensor2: float
    ProximitySensor3: float
    ProximitySensor4: float
    def __init__(self, ProximitySensor1: _Optional[float] = ..., ProximitySensor2: _Optional[float] = ..., ProximitySensor3: _Optional[float] = ..., ProximitySensor4: _Optional[float] = ...) -> None: ...

class Telemetry(_message.Message):
    __slots__ = ("GpsAdditionalFlags", "GpsDay", "GpsFixStatusFlags", "GpsHour", "GpsLatitude", "GpsLongitude", "GpsMinute", "GpsMonth", "GpsSecond", "GpsValidityFlags", "GpsYear", "MpuAccelerationX", "MpuAccelerationY", "MpuAccelerationZ", "MpuRotationX", "MpuRotationY", "MpuRotationZ", "MpuTemperature")
    GPSADDITIONALFLAGS_FIELD_NUMBER: _ClassVar[int]
    GPSDAY_FIELD_NUMBER: _ClassVar[int]
    GPSFIXSTATUSFLAGS_FIELD_NUMBER: _ClassVar[int]
    GPSHOUR_FIELD_NUMBER: _ClassVar[int]
    GPSLATITUDE_FIELD_NUMBER: _ClassVar[int]
    GPSLONGITUDE_FIELD_NUMBER: _ClassVar[int]
    GPSMINUTE_FIELD_NUMBER: _ClassVar[int]
    GPSMONTH_FIELD_NUMBER: _ClassVar[int]
    GPSSECOND_FIELD_NUMBER: _ClassVar[int]
    GPSVALIDITYFLAGS_FIELD_NUMBER: _ClassVar[int]
    GPSYEAR_FIELD_NUMBER: _ClassVar[int]
    MPUACCELERATIONX_FIELD_NUMBER: _ClassVar[int]
    MPUACCELERATIONY_FIELD_NUMBER: _ClassVar[int]
    MPUACCELERATIONZ_FIELD_NUMBER: _ClassVar[int]
    MPUROTATIONX_FIELD_NUMBER: _ClassVar[int]
    MPUROTATIONY_FIELD_NUMBER: _ClassVar[int]
    MPUROTATIONZ_FIELD_NUMBER: _ClassVar[int]
    MPUTEMPERATURE_FIELD_NUMBER: _ClassVar[int]
    GpsAdditionalFlags: float
    GpsDay: float
    GpsFixStatusFlags: float
    GpsHour: float
    GpsLatitude: float
    GpsLongitude: float
    GpsMinute: float
    GpsMonth: float
    GpsSecond: float
    GpsValidityFlags: float
    GpsYear: float
    MpuAccelerationX: float
    MpuAccelerationY: float
    MpuAccelerationZ: float
    MpuRotationX: float
    MpuRotationY: float
    MpuRotationZ: float
    MpuTemperature: float
    def __init__(self, GpsAdditionalFlags: _Optional[float] = ..., GpsDay: _Optional[float] = ..., GpsFixStatusFlags: _Optional[float] = ..., GpsHour: _Optional[float] = ..., GpsLatitude: _Optional[float] = ..., GpsLongitude: _Optional[float] = ..., GpsMinute: _Optional[float] = ..., GpsMonth: _Optional[float] = ..., GpsSecond: _Optional[float] = ..., GpsValidityFlags: _Optional[float] = ..., GpsYear: _Optional[float] = ..., MpuAccelerationX: _Optional[float] = ..., MpuAccelerationY: _Optional[float] = ..., MpuAccelerationZ: _Optional[float] = ..., MpuRotationX: _Optional[float] = ..., MpuRotationY: _Optional[float] = ..., MpuRotationZ: _Optional[float] = ..., MpuTemperature: _Optional[float] = ...) -> None: ...

class TelemetryData(_message.Message):
    __slots__ = ("B3", "Battery", "BatteryFaults", "Contactor", "KeyMotor", "MBMS", "MPPT", "MotorDetails0", "MotorDetails1", "Pi", "ProximitySensors", "Telemetry", "TimeStamp", "Title")
    B3_FIELD_NUMBER: _ClassVar[int]
    BATTERY_FIELD_NUMBER: _ClassVar[int]
    BATTERYFAULTS_FIELD_NUMBER: _ClassVar[int]
    CONTACTOR_FIELD_NUMBER: _ClassVar[int]
    KEYMOTOR_FIELD_NUMBER: _ClassVar[int]
    MBMS_FIELD_NUMBER: _ClassVar[int]
    MPPT_FIELD_NUMBER: _ClassVar[int]
    MOTORDETAILS0_FIELD_NUMBER: _ClassVar[int]
    MOTORDETAILS1_FIELD_NUMBER: _ClassVar[int]
    PI_FIELD_NUMBER: _ClassVar[int]
    PROXIMITYSENSORS_FIELD_NUMBER: _ClassVar[int]
    TELEMETRY_FIELD_NUMBER: _ClassVar[int]
    TIMESTAMP_FIELD_NUMBER: _ClassVar[int]
    TITLE_FIELD_NUMBER: _ClassVar[int]
    B3: B3
    Battery: BatteryStatus
    BatteryFaults: BatteryFaults
    Contactor: ContactorStatus
    KeyMotor: KeyMotor
    MBMS: MBMS
    MPPT: MPPT
    MotorDetails0: MotorDetails
    MotorDetails1: MotorDetails
    Pi: Pi
    ProximitySensors: ProximitySensors
    Telemetry: Telemetry
    TimeStamp: int
    Title: str
    def __init__(self, B3: _Optional[_Union[B3, _Mapping]] = ..., Battery: _Optional[_Union[BatteryStatus, _Mapping]] = ..., BatteryFaults: _Optional[_Union[BatteryFaults, _Mapping]] = ..., Contactor: _Optional[_Union[ContactorStatus, _Mapping]] = ..., KeyMotor: _Optional[_Union[KeyMotor, _Mapping]] = ..., MBMS: _Optional[_Union[MBMS, _Mapping]] = ..., MPPT: _Optional[_Union[MPPT, _Mapping]] = ..., MotorDetails0: _Optional[_Union[MotorDetails, _Mapping]] = ..., MotorDetails1: _Optional[_Union[MotorDetails, _Mapping]] = ..., Pi: _Optional[_Union[Pi, _Mapping]] = ..., ProximitySensors: _Optional[_Union[ProximitySensors, _Mapping]] = ..., Telemetry: _Optional[_Union[Telemetry, _Mapping]] = ..., TimeStamp: _Optional[int] = ..., Title: _Optional[str] = ...) -> None: ...
